version: '3'

services:
  postgres:
    image: 'postgres:12'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: 'pguser'
      POSTGRES_PASSWORD: 'supersecretpassword'
      POSTGRES_DB: 'draw-board'
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  api_service:
    build: .
    ports:
      - '8080:8080'
    environment:
      spring.datasource.url: 'jdbc:postgresql://postgres:5432/draw-board'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/draw-board'
      SPRING_DATASOURCE_USERNAME: 'pguser'
      SPRING_DATASOURCE_PASSWORD: 'supersecretpassword'
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'create-drop'
    # volumes:
    #   - ./core-service:/*/
    # restart: always
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
volumes:
  pgdata: {}
